- IQKeybordManagerSwift/IQKeyboardManager.swift
I was getting a nil value from the responderViews function in removeToolbarIfRequired() when I set the enableAutoToolbar property to false.
> Added check for nil return from responderViews()

- IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift
Hey, i did see the last commit #283 and have a little bug, on the `IQUIView+IQKeyboardToolbar.swift` u call the previous action instead the next, so i made the fix. Super small fix. 
```
649 next = IQBarButtonItem(image: UIImage(named: "IQButtonBarArrowRight", inBundle: bundle, compatibleWithTraitCollection: nil), style: UIBarButtonItemStyle.Plain, target: target, action: nextAction)
```
> Next action on the next toolbar button fix

- IQKeyboardManagerSwift/Resources/Info.plist
Carthage build process needs an Info.plist file to be present and correctly filled.
If the file is missing, compilation ends with an error. If the file is empty, simulator (and the device) is unable to run.
See [#297](https://github.com/hackiftekhar/IQKeyboardManager/pull/297)
> Add missing Info.plist for Carthage compatibility

- IQKeyboardManagerSwift/IQKeyboardManager.swift
This resolves https://github.com/hackiftekhar/IQKeyboardManager/issues/338. For the particular use case, most users would expect that their touch would trigger a selection in a view rather than having to tap a second time.
I'm happy to add an option to enable/disable this like `shouldResignOnTouchOutside` if this is not the desired behaviour for all users.
> Pass through touches when resigning on touch outside

- IQKeyBoardManager/IQKeyboardManager.m
- IQKeyboardManagerSwift/IQKeyboardManager.swift
Sorry, I made a mistake with #363, it should be set to false/NO so it doesn't interrupt any touches through to the content underneath.
> Set cancels touches in view to false/NO

- IQKeyBoardManager/IQToolbar/IQBarButtonItem.m
UIBarButtonItemStyleBordered is deprecated since iOS 8. Replaced in favor of UIBarButtonItemStylePlain.
> UIBarButtonItemStyleBordered fix

- Demo/Swift_Demo/Resources/Info.plist
Otherwise the resulting framework wouldn't be readable by XCode; "Failed to read file or folder at .../.framework"
> Fixed Info.plist for Carthage

- Demo/Objective_C_Demo/Resources/Info.plist
This pull request changes the Info.plist bundle OS type code of the IQKeyboardManager scheme to framework so that `carthage build` does not fail.
> Change Info.plist bundle OS type code to framework

- IQKeyboardManagerSwift/IQKeyboardManager.swift
Keyboard was not pushing text fields up when animating in.
Casting of the UIKeyboard userInfo was not correct.
`as AnyObject` has been changed to `as? NSNumber` or `as? NSValue` for numbers and NSRect types respectively.
> Fixed keyboard not showing in Swift3-Beta6

- Demo/Swift_Demo/Resources/Info.plist
Remove the armv7 requirement from the Swift Demo's Info.plist. It would appear
that its presence prevents apps that link against the IQKeyboardManagerSwift
framework cannot be submitted to the store if this flag is present.
iTunesConnect error message: [Transporter Error Output]: ERROR ITMS-90689:
"Invalid Info.plist key. The key 'UIRequiredDeviceCapabilities' in bundle
MyApp.app/Frameworks/IQKeyboardManagerSwift.framework is invalid for frameworks"
Related to #706.
> Remove UIRequiredDeviceCapabilities from Info.plist

- README.md
The link formatting in the readme was causing a couple of the links to be broken. This fixes that.
> Fix known issues and manual management readme links

- KNOWN ISSUES.md
- MANUAL MANAGEMENT.md
- PROPERTIES & FUNCTIONS.md
- README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- IQKeyboardManager/IQTextView/IQTextView.m
- IQKeyboardManagerSwift/IQTextView/IQTextView.swift
The placeholder is alignment with the cursor.
This is before:
This is after:
> [IQTextView] correct aligment with placeholder and the cursor

- IQKeyboardManagerSwift/IQTextView/IQTextView.swift
IQTextView's uses a constant value to position the placeholderLabel, setting the textContainer's insets is being ignored. This PR  fixes that.
> Use textcontainerInset and lineFragmentPadding for placeholderLabel position in IQTextView

- IQKeyboardManager/IQKeyboardManager.h
- IQKeyboardManager/IQTextView/IQTextView.m
- IQKeyboardManager/IQToolbar/IQToolbar.m
Fixed #934 
It was caused by a build failure of the Objective-C target. (Xcode8.3.3)
So, I added missing import statements corresponding to some classes and properties.
> Fixed a bug that failed to build Objective-C target.

- IQKeyboardManagerSwift/IQKeyboardManager.swift
To avoid app crash, I added the logic to check if siblings is not empty. 
On iOS 11, siblings in `IQKeyboardManager` is empty in some cases as shown in the screenshots below.
> [iOS 11] Fix the bug that app crashes when siblings is empty

- IQKeyboardManagerSwift/IQKeyboardManager.swift
That will make these methods available from objc. In our project, we have a majority of Swift but still few ObjC code left, for the objc ones, we still need to access to these methods.
> Add missing @objc to IQKeyboardManager.swift

- README.md
This pull request corrects the spelling of **CocoaPods** 🤓
https://github.com/CocoaPods/shared_resources/tree/master/media
> Correct the spelling of CocoaPods in a README

- IQKeyboardManagerSwift/IQTextView/IQTextView.swift
characters array is deprecated, String has cost directly, but in this case is most secure to use Empty property
> suppress deprecation warning

- LICENSE.md
- README.md
Reformatted LICENSE.md slightly, so GitHub will pick up license type (MIT) automatically and display it on related badges. Right now it shows `license: Other`.
Also removed unneeded apostrophes in code block (introduced in my previous PR, sorry for that).
> Update LICENSE formatting, fix README typo

- IQKeyboardManager/IQKeyboardManager.h
> fix umbreall warning when use objc framework by carthage

- IQKeyboardManager.xcodeproj/project.pbxproj
The deployment targets in the Readme are 8.0, but the project file does not reflect this and has a value of 11.1.
This minor change fixes this situation.
> Fix the deployment targets

- IQKeyboardManager.xcodeproj/project.pbxproj
- IQKeyboardManagerSwift/IQKeyboardManager.swift
- IQKeyboardManagerSwift/IQToolbar/IQBarButtonItem.swift
- IQKeyboardManagerSwift/IQToolbar/IQInvocation.swift
- IQKeyboardManagerSwift/IQToolbar/IQTitleBarButtonItem.swift
Hi, i recently used the code below to assign done button custom function. But this created retain cycle and controller did not released from memory when it should. 
`textField.doneBarButton.setTarget(self, action: #selector(doCustomWork(sender:)))`
i made a little change to see if i can fix the issue. I created little class to use instead of tupple and made it weak. This change solved my issue.
> This pull request is not completed, sorry about that. i want to hear your opinions.
> i didn't had time to test objective version yet. 
Thank you.
-
> IQBarButtonItem Invocation retain cycle problem - Swift Version

- IQKeyboardManagerSwift/Categories/IQUIScrollView+Additions.swift
- IQKeyboardManagerSwift/Categories/IQUITextFieldView+Additions.swift
- IQKeyboardManagerSwift/Categories/IQUIView+Hierarchy.swift
- IQKeyboardManagerSwift/Categories/IQUIViewController+Additions.swift
- IQKeyboardManagerSwift/Constants/IQKeyboardManagerConstants.swift
- IQKeyboardManagerSwift/IQKeyboardManager.swift
- IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift
- IQKeyboardManagerSwift/IQTextView/IQTextView.swift
- IQKeyboardManagerSwift/IQToolbar/IQBarButtonItem.swift
- IQKeyboardManagerSwift/IQToolbar/IQInvocation.swift
- IQKeyboardManagerSwift/IQToolbar/IQTitleBarButtonItem.swift
- IQKeyboardManagerSwift/IQToolbar/IQToolbar.swift
- IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift
Annotated members with @objc to make them available to Objective C classes in mixed projects
Fixes # [1294](https://github.com/hackiftekhar/IQKeyboardManager/issues/1294#issuecomment-379334390)
> Swift 4.1 @objc annotations

- IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m
Hello! Thank you for excellent library! After a recent update I found out that the next button image is incorrect in the ObjC version of the library running under iOS 9.3 (Swift version is ok):
I think there's a copy/paste error in `keyboardNextImage` method.
> Fixed keyboard next image in 

- IQKeyboardManager/IQTextView/IQTextView.m
- IQKeyboardManagerSwift/IQTextView/IQTextView.swift
Fixed IQTextView intrinsic size when placeholder text is more than 2 lines.
> Fixed IQTextView intrinsic size when placeholder text is more than 2 lines.

- IQKeyboardManager/IQKeyboardManager.m
The `+ (void)load` method takes more time in main thread when app launch, It affects the startup of the program. I just want introduce this feature that can control in `GCC_PREPROCESSOR_DEFINITIONS` style. Adding a **MACRO** to support  disable `+ (void)load` method in build setting configurations. 
Aim to  [https://github.com/hackiftekhar/IQKeyboardManager/issues/1428](https://github.com/hackiftekhar/IQKeyboardManager/issues/1428)
Note: non-breaking change which adds functionality
Using Cocoapods like that:
```ruby
post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == 'IQKeyboardManager'
target.build_configurations.each do |config|
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)'] …
```
> Support build setting in configuration to disable `+ (void)load` method

- IQKeyboardManager/IQKeyboardManager.m
- IQKeyboardManagerSwift/IQKeyboardManager.swift
Thanks for this great work! 
I found there is useless for `registeredClasses` and not a public `property`, so should we remove it ?
[performance] Remove useless container
Best Regards
> [performance]Remove useless container

- README.md
IQKeyboardManager can be installed using Swift Package Manager. However, there is no guideline on how to do it in `README.md`. This PR adds the guideline on how to install IQKeyboardManager both by adding the link to this repo in `Package.swift` and through Xcode 11 UI.
> Add Swift Package Manager install guides

- IQKeyboardManager/IQKeyboardManager.h
- IQKeyboardManager/IQKeyboardManager.m
- IQKeyboardManager/IQToolbar/IQToolbar.m
- IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.m
- IQKeyboardManagerSwift/IQKeyboardManager.swift
- IQKeyboardManagerSwift/IQToolbar/IQToolbar.swift
- IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift
We propose this simple change to be able to change the AccessibilityLabel in the buttons of the bar that's located over the keyboard. Actually we can change the title, but the AccessibilityLabel is hardcoded. 
We add 3 new properties in the shared manager to pass a custom text (if the user don't change the value, the behavior is the same of the actual version)
> [i18n] Add localization support for AccessibilityLabel in BarButtonItems

- IQKeyboardManager/Categories/IQUIScrollView+Additions.h
- IQKeyboardManager/Categories/IQUIScrollView+Additions.m
- IQKeyboardManager/IQKeyboardManager.m
- IQKeyboardManagerSwift/Categories/IQUIScrollView+Additions.swift
- IQKeyboardManagerSwift/IQKeyboardManager.swift
Unless I missed something, your library does not handle the case where the scroll view is pinned to a footer view which should go on top of the keyboard.
In this specific case, I need to handle the keyboard resizing manually and the best thing to do is deactivate IQKeyboardManagerSwift for touching contentInset since I'm touching somehow the frame at the same time (with an autolayout constraint for example)
Without the content of this PR, this is the issue (on 6.2.0, 6.3.0 seems to have improved the way it works)
Bug with 6.2.0
I think it is a way of handling this situation https://github.com/hackiftekhar/IQKeyboardManager/wiki/IQKeyboardManager-6.0.0-Migration-Guide#known-issues
> Added support to disable content inset adjustment on keyboard apparition

- IQKeyboardManagerSwift/Categories/IQNSArray+Sort.swift
- IQKeyboardManagerSwift/Categories/IQUIScrollView+Additions.swift
- IQKeyboardManagerSwift/Categories/IQUITextFieldView+Additions.swift
- IQKeyboardManagerSwift/Constants/IQKeyboardManagerConstantsInternal.swift
- IQKeyboardManagerSwift/IQKeyboardManager+Debug.swift
- IQKeyboardManagerSwift/IQKeyboardManager+Internal.swift
- IQKeyboardManagerSwift/IQKeyboardManager+OrientationNotification.swift
- IQKeyboardManagerSwift/IQKeyboardManager+Position.swift
- IQKeyboardManagerSwift/IQKeyboardManager+Toolbar.swift
- IQKeyboardManagerSwift/IQKeyboardManager+UIKeyboardNotification.swift
- IQKeyboardManagerSwift/IQKeyboardManager+UITextFieldViewNotification.swift
- IQKeyboardManagerSwift/IQKeyboardManager.swift
- IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift
- IQKeyboardManagerSwift/IQToolbar/IQBarButtonItem.swift
- IQKeyboardManagerSwift/IQToolbar/IQTitleBarButtonItem.swift
When **manually** implementing this, Xcode will throw **Red** errors about "Use of undeclared type" of UIKit types and break the code, so i fixed it with UIKit imports and commented Foundation that is redundant because UIKit contains Foundation.
Fixes # Use of undeclared type of UIKit elements
> IQKeyboardManagerSwift - Was required UIKit imports

- IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift
`UIScree.main` will be deprecated in a future version of iOS.
I used Use `UIApplication` and `view.windowScene.screen` to get display's scale.
developer doc > [mian](https://developer.apple.com/documentation/uikit/uiscreen/1617815-main) already deprecated. It causes serious errors in the near future.
So have to change another way. And `UIApplication` and `view.windowScene.screen` is the others way of getting display's scale. That is available from `iOS 13.0`. This is why control flow has `iOS 13.0` condition.
Fixes #1988
> Use `UIApplication` and `view.windowScene.screen` instead of `UIScreen.main` on iOS 13.0 and later

- IQKeyboardManager/PrivacyInfo.xcprivacy
- IQKeyboardManagerSwift/PrivacyInfo.xcprivacy
IQKeyboardManager privacy data missing in the application privacy report.
[Reference](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
Fixes #2012
> fix: privacy manifest collected data type record updated

- Package.swift
Currently privacy manifest file doesn't handle by Swift Package Manger. To add the SDK privacy manifest into app bundle need to add as resource into the target.
**To Reproduce**
Steps to reproduce the behavior:
1. Add the dependency by Swift Package Manager
2. Archive the app.
3. Generate the privacy report and save to disk.
4. Check the report, didn't find the IQKeyboardManager privacy report.
**Expected behavior**
There should be seperate segment for IQKeyboardManager in the privacy report
> fix: privacy manifest file specified by Swift Package Manager

- IQKeyboardManager/IQTextView/IQTextView.m
- IQKeyboardManagerSwift/IQTextView/IQTextView.swift
Fixed Cursor Position in Centered aligned TextView is wrong #196 in Objective-C and Swift.
#1967 
Cosmetic Change
> Fixed TextView cursor issue

- IQKeyboardManager/PrivacyInfo.xcprivacy
- IQKeyboardManagerSwift/PrivacyInfo.xcprivacy
- As commented by [this](https://github.com/hackiftekhar/IQKeyboardManager/pull/2013#issuecomment-1954555108), there are unnecessary empty values in the PrivacyInfo.xcprivacy file.
- Unlike the other libraries, only IQKeyboardManager exposes an empty Additional Data item in PrivacyInfoReport, which I think is unnecessary
- Added a default value
Fixes #2013
> Remove unnecessary value from privacy manifest file
