IQKeyBoardManager/IQKeyboardManager.m

More about:
https://github.com/hackiftekhar/IQKeyboardManager/issues/326

Redundant super call in +load method removed

---

IQKeyboardManagerSwift.xcodeproj/project.pbxproj
IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift

Fix issue #324  as described.
Tested on the project where I use this library.

Swift 2.1 UIReturnKeyType fix

---

Demo/Swift_Demo/Resources/Info.plist
IQKeyboardManager.xcodeproj/project.pbxproj
IQKeyboardManagerSwift.xcodeproj/project.pbxproj
IQKeyboardManagerSwift.xcodeproj/xcshareddata/xcschemes/IQKeyboardManagerSwift.xcscheme

Updated project settings for Xcode 7 and removed the Info.plist from resource bundle (was causing an error)

Xcode 7 Warning and Project Settings

---

Demo/Swift_Demo/AppDelegate.swift
Demo/Swift_Demo/ViewController/BottomBlankSpaceViewController.swift
Demo/Swift_Demo/ViewController/CollectionViewDemoController.swift
Demo/Swift_Demo/ViewController/CustomViewController.swift
Demo/Swift_Demo/ViewController/ExampleTableViewController.swift
Demo/Swift_Demo/ViewController/ManualToolbarViewController.swift
Demo/Swift_Demo/ViewController/NavigationBarViewController.swift
Demo/Swift_Demo/ViewController/ScrollViewController.swift
Demo/Swift_Demo/ViewController/SettingsViewController.swift
Demo/Swift_Demo/ViewController/SpecialCaseViewController.swift
Demo/Swift_Demo/ViewController/TableViewInContainerViewController.swift
Demo/Swift_Demo/ViewController/TextFieldViewController.swift
Demo/Swift_Demo/ViewController/TextSelectionViewController.swift
Demo/Swift_Demo/ViewController/TextViewSpecialCaseViewController.swift
Demo/Swift_Demo/ViewController/ViewController.swift
IQKeyboardManagerSwift/Categories/IQUIView+Hierarchy.swift
IQKeyboardManagerSwift/IQKeyboardManager.swift
IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift
IQKeyboardManagerSwift/IQToolbar/IQTitleBarButtonItem.swift
IQKeyboardManagerSwift/IQToolbar/IQToolbar.swift
IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift

Added compatibility with Xcode 8 Beta 6.
Closes #531.

Swift3 Xcode 8 Beta 6

---

IQKeyboardManagerSwift/IQKeyboardManager.swift

Add @discardableResult to goPrevious(),goNext(),resignFirstResponder()

---

IQKeyboardManagerSwift/IQKeyboardManager.swift
IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift

Update code style: to Swift3.1

---

IQKeyboardManager/IQKeyboardManager.m
IQKeyboardManagerSwift/IQKeyboardManager.swift

this will allow ui test to run faster

only animate when UI kit allows

---

IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift

Bug fix (non-breaking change which fixes an issue)

Fix left/right toolbar buttons

---

IQKeyboardManager/IQToolbar/IQUIView+IQKeyboardToolbar.h

Delete warnings due to missing nullability type specifiers.

Add missing nullability type specifiers

---

Package.swift

We at JamitLabs developed a dependency management system relying on the Swift Package Manager and as we included your framework in one of our projects we need to have the Package.swift file, so I added it. For further reading please check https://github.com/JamitLabs/Accio.
Being able to get the framework over Swift PackageManager

Preparations for usage with Accio (https://github.com/JamitLabs/Accio)

---

IQKeyboardManager/IQKeyboardManager.h
IQKeyboardManager/IQKeyboardManager.m
IQKeyboardManagerSwift/IQKeyboardManager.swift

Added closure for handle property movedDistance

Added closure for handle property movedDistance

---

IQKeyboardManager/IQKeyboardManager.h

Fix typos in IQKeyboardManager.h

Fix typos in IQKeyboardManager.h

---

IQKeyboardManager/IQTextView/IQTextView.m

LayoutIfNeeded is not needed for each callback
Fixes #1783

Fixed#1783

---

IQKeyboardManager/IQKeyboardManager.m

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

remove UIAlertView

---

Demo/Objective_C_Demo/Storyboard/Base.lproj/General.storyboard
Demo/Objective_C_Demo/ViewController/TextFieldViewController.m

when I run "DemoObjc" project, I found error message is "*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<TextFieldViewController 0x103b071f0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key textView1.'"
So this issue solved!
- [v] Bug fix (non-breaking change which fixes an issue)

Terminating app due to uncaught exception Bug Fix in Objective-C

---

Package.swift

Updated swift-tools-version in Package.swift

Updated swift-tools-version in Package.swift

---

IQKeyboardManagerSwift/IQTextView/IQPlaceholderable.swift

- add missing import UIKit
Type of change

-Fixed Cannot find type 'UITextField' in scope

---

IQKeyboardManager.podspec.json
IQKeyboardManagerSwift.podspec.json

Change PrivacyInfo.xcprivacy file resource to resource_bundles

---

Package.swift

Fixes compilation on Xcode 15.2+ for issue: https://github.com/hackiftekhar/IQKeyboardManager/issues/2024

Update Package.swift to include platform for Xcode 15.2+

---

MIGRATION GUIDE 6.0 TO 7.0.md

Just a small fix in the documentation.

Update MIGRATION GUIDE 6.0 TO 7.0.md

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Improvement README.md

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

docs: edited the MIT license link icon
